http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:   
  oms:
    host: '*'
    paths: '/resources/v1/*'
  bb:
    host: '*'
    paths: '/perpule-prod/bigbazaar/*'
serviceEndpoints:  
  omsService:
    url: 'https://perpule-1248.appspot.com'
  bbService:
    url:  'http://34.210.250.70:8080'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy 
  - rate-limit
pipelines:  
- name: default
  apiEndpoints:      
      - oms
      - bb
  policies:
    - proxy:
      - action:
         serviceEndpoint: omsService        
         changeOrigin: true
      - action:
         serviceEndpoint: bbService        
         changeOrigin: true
     
